---
- name: Install MySQL
  apt: name={{item}} state=installed
  with_items:
    - mysql-server-5.6
    - python-mysqldb
- name: Generate new root password
  command: openssl rand -hex 7 creates=/root/.my.cnf
  register: mysql_new_root_pass
- name: Remove anonymous users
  mysql_user: name="" state=absent
- name: Remove test database
  mysql_db: name=test state=absent
- name: Update root password
  mysql_user: name=root host={{item}} password={{mysql_new_root_pass.stdout}}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: mysql_new_root_pass.changed
- name: Create my.cnf
  template: src=my.cnf dest=/root/.my.cnf
  when: mysql_new_root_pass.changed
- name: Output new root password
  debug: msg="New root password is {{mysql_new_root_pass.stdout}}"
  when: mysql_new_root_pass.changed
