---
- name: Add the ondrej PHP PPA
  apt_repository: repo='ppa:ondrej/php'
- name: Update the apt cache
  apt: update_cache=yes cache_valid_time=3600
- name: Install PHP
  apt: name={{item}} state=installed
  with_items:
    - php7.1
    - php7.1-fpm
    - php7.1-mysql
    - php7.1-xml
- name: Remove apache2
  apt: name=apache2 state=removed