---
- name: Install nginx
  apt: name=nginx state=installed
- name: Start nginx
  service: name=nginx state=started
- name: Create nginx config
  template: src=default dest=/etc/nginx/sites-available/default
  notify: restart nginx